channels:
- conda-forge
dependencies:
- python=3.11.1
- pip<=24.3.1
- pip:
  - mlflow==2.16.2
  - astunparse==1.6.3
  - cloudpickle==3.0.0
  - dill==0.3.8
  - numpy==1.24.3
  - pandas==2.1.3
  - torch==2.4.1
  - tqdm==4.67.0
name: mlflow-env
